name: pudding
broker: redis
messageQueue: pulsar
scheduler_config:
  time_slice_interval: 60s
redis_config:
  url: redis://default:default@localhost:6379/11
  dial_timeout: 20
pulsar_config:
  url: pulsar://localhost:6650
  connection_timeout: 10
  producers_config:
    - topic: token
      batching_max_publish_delay: 10
      batching_max_messages: 100
      batching_max_size: 5
    - topic: test_topic_1
      # BatchingMaxPublishDelay specifies the time period within which the messages sent will be batched (default: 10ms)
      batching_max_publish_delay: 10
      batching_max_messages: 100
      # BatchingMaxSize specifies the maximum number of bytes permitted in a batch. xxKB
      batching_max_size: 5
    - topic: test_topic_2
      batching_max_publish_delay: 10
      batching_max_messages: 100
      batching_max_size: 5

log_config:
  default:
    level: debug
    writers:
      - console
      - file
    format: json
    file_config:
      # log file path
      filepath: ./log/server.log
      # file max_age
      max_age: 7
      # max backup files
      max_backups: 7
      # max file size, MB
      max_size: 128
      # log file is compress
      compress: false
  pulsar_log:
    level: debug
    writers:
      - file
    format: json
    file_config:
      # log file path
      filepath: ./log/pulsar.log
      # file max_age
      max_age: 7
      # max backup files
      max_backups: 7
      # max file size, MB
      max_size: 128
      # log file is compress
      compress: false
  grpc_log:
    level: debug
    writers:
      - console
      - file
    format: json
    file_config:
      # log file path
      filepath: ./log/grpc.log
      # file max_age
      max_age: 7
      # max backup files
      max_backups: 7
      # max file size, MB
      max_size: 128
      # log file is compress
      compress: false

