name: pudding
time: 2022
broker: redis
messageQueue: pulsar
schedulerConfig:
  timeSliceInterval: 60s
redisConfig:
  redisURL: redis://default:default@localhost:6379/11
  dialTimeout: 20
pulsarConfig:
  pulsarURL: pulsar://localhost:6650
  connectionTimeout: 10
  producersConfig:
    - topic: token
      batchingMaxPublishDelay: 10
      batchingMaxMessages: 100
      batchingMaxSize: 5
    - topic: test_topic_1
      # BatchingMaxPublishDelay specifies the time period within which the messages sent will be batched (default: 10ms)
      batchingMaxPublishDelay: 10
      batchingMaxMessages: 100
      # BatchingMaxSize specifies the maximum number of bytes permitted in a batch. xxKB
      batchingMaxSize: 5
    - topic: test_topic_2
      batchingMaxPublishDelay: 10
      batchingMaxMessages: 100
      batchingMaxSize: 5

log_config:
  default:
    level: debug
    writers:
      - stdout
    format: json
    file_config:
      # log file path
      filepath: ./log/server.log
      # file max_age
      max_age: 7
      # max backup files
      max_backups: 7
      # max file size, MB
      max_size: 128
      # log file is compress
      compress: false
  pulsar_log:
    level: debug
    writers:
      - stdout
    format: json

