name: pudding.broker
server_config:
  host-domain: "localhost"
  grpc_port: 50051
  http_port: 8080
  enable_tls: true
  cert_path: ./certs/pudding.pem
  key_path: ./certs/pudding-key.pem
  name_server_url: http://consul-client:8500
  etcd_urls: http://etcd-host:2379

  broker: redis
  connector: kafka
  time_slice_interval: 60s
  message_topic: default
  token_topic: token

log_config:
  - log_name: default
    level: debug
    writers:
      - console
      - file
    file_config:
      filepath: ./log/server.log
  - log_name: kafka_log
    level: info
    writers:
      - file
    file_config:
      filepath: ./log/kafka.log
  - log_name: grpc_log
    level: info
    writers:
      - console
      - file
    file_config:
      filepath: ./log/grpc.log

redis_config:
  url: redis://default:default@redis-host:6379/11
  dial_timeout: 20
kafka_config:
  address: kafka-host:9092
  batch_size: 100
  producer_batch_timeout: 50

