name: lint-and-test
on:
  push:
    tags:
      - v*
      - main
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20'
          cache: false
      - uses: bufbuild/buf-setup-action@v1
      - run: make gen/proto
      - run: cd api/protobuf-spec && buf mod update && buf lint
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.15.1'
      - name: Install Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Cache Docker layers
#        uses: actions/cache@v3
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-
      - name: Init unittest environment
        run: make env/test
      - name: Run unittest
        run: make test/run
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#      -
#        # Temp fix
#        # https://github.com/docker/build-push-action/issues/252
#        # https://github.com/moby/buildkit/issues/1896
#        name: Move cache
#        run: |
#          rm -rf /tmp/.buildx-cache
#          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  build:
    runs-on: ubuntu-latest
    needs: [golangci-lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0