name: lint-and-test
on:
  push:
    tags:
      - v*
      - main
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.20'
          cache: false
      - uses: bufbuild/buf-setup-action@v1
      - run: make gen/proto
      - run: cd api/protobuf-spec && buf mod update && buf lint
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.15.1'
      - name: Install Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Init unittest environment
        run: make env/test
      - name: Run unittest
        run: make test/run
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: [golangci-lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4