on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.17.x, 1.18.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
  # Label of the container job
  runner-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      pulsar:
        # Docker Hub image
        image: apachepulsar/pulsar
        # Set health checks to wait until pulsar has started
        options: >-
          --health-cmd "curl -fs http://localhost/8080 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 6650:6650
          - 8080:8080

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...