on: [pull_request]
name: Test
jobs:

  # Label of the container job
  test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Apache Pulsar
        uses: reugn/github-action-pulsar@v1

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0.31'
          root-password: 'my-secret-pw'
      - run: mysql -u root -h 127.0.0.1 -p'my-secret-pw' -e 'create database test;'
      - name: Install Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Go Mod Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Test
        run: go test ./...