on: [push, pull_request]
name: Test
jobs:

  # Label of the container job
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    # Docker Hub image that `container-job` executes in
    container: golang:1.19
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      pulsar:
        # Docker Hub image
        image: apachepulsar/pulsar
        # Set health checks to wait until pulsar has started
        options: >-
          --health-cmd "curl -fs http://localhost:8080/admin/v2/brokers/healthcheck/ || exit 1"
          --health-interval 20s
          --health-timeout 2m
          --health-retries 6
        ports:
          # Maps tcp port 5432 on service container to the host
          - 6650:6650
          - 8080:8080

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...